### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by davityavryan** [elemental-design/i18next-react-mdx#1]
Hey @macintoshhelper 

I think you are missing dependencies in package.json. I would guess that you need `peerDependecy` of `react` and a `dependency` of `@mdx-js/runtime`.

If you agree, I can also create a PR.

**Comment by macintoshhelper** [comment]
Thanks for the offer, faster to do it myself though; I’ve added `react` to `optionalDependencies`, there are some issues around using `peerDependencies` `react >= 16` and `react@17`. And added `@mdx-js/runtime` as a dependency.

**Comment by macintoshhelper** [comment]
When it comes to the `Demo` component, you can use JSX inside of `mdx`: https://mdxjs.com/advanced/components

e.g.

```js
{
  "demo_md": "Hello world! <Demo>This is a custom component</Demo>"
}
```

Seems that I’ve managed to get `peerDependencies` working, `npm` caused a tonne of stuff to break by auto-installing peer dependencies… Reference of the fix: https://github.com/facebook/react/commit/e7006d67dff2b9d3a9545204a469f32c70d52a8b

**Comment by davityavryan** [comment]
Great, thanks. ;)

**Comment by davityavryan** [comment]
oh my god the dependency tree :)
are you sure MDX is the one that should be used? :D

https://bundlephobia.com/package/i18next-react-mdx@0.0.4

**Comment by davityavryan** [comment]
p.s. note from package itself [https://www.npmjs.com/package/@mdx-js/runtime](https://www.npmjs.com/package/@mdx-js/runtime)

> ⚠️ warning: this is not the preferred way to use MDX since it introduces a substantial amount of overhead and dramatically increases bundle sizes. It should also not be used with user input that isn’t sandboxed.

**Comment by macintoshhelper** [comment]
Ugh, yeah, MDX bundles Babel runtime, didn't realise it was that large; markdown/mdx should really be used with a compilation step (Webpack/Rollup). Any ideas on a nice way to integrate this? Will probably have to bypass JSON locales and go for JS imports of an `.md` file. `marksy` custom component support is buggy and Storybook have replaced it with a Webpack MDX build step. I might implement a custom file backend that uses Webpack.

If you explicitly need runtime JSON support, I can integrate `markdown-to-jsx`.

**Comment by macintoshhelper** [comment]
I've published `i18next-react-md` using `markdown-to-jsx`, which is much more lightweight. MDX is probably overkill for a single line markdown snippet in a locale JSON file. Let me know if there's any issues. Use `joinArrays: '\n'` for multiline markdown in the locale JSON.

I'll work on a compilation and dynamic import backend for `i18next-react-mdx` later.
